# Generated by Django 3.1.7 on 2021-03-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_userprofilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='userProfilePic',
            field=models.ImageField(upload_to='phot_upload'),
        ),
    ]
