# Generated by Django 3.1.7 on 2021-03-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fanclub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('des', models.TextField()),
                ('club_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='userName',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='userPassword',
            new_name='user_password',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='userProfilePic',
            new_name='user_profile_pic',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userPassword',
            new_name='user_password',
        ),
    ]
