# Generated by Django 3.1.7 on 2021-03-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20210308_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following_clubs',
            field=models.ManyToManyField(to='todo.Fanclub'),
        ),
    ]
