# Generated by Django 3.1.7 on 2021-03-09 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_auto_20210309_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanclub',
            name='admin_members',
            field=models.ManyToManyField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='todo.user'), related_name='admin_members', to='todo.User'),
        ),
        migrations.AlterField(
            model_name='fanclub',
            name='banned_users',
            field=models.ManyToManyField(blank=True, related_name='banned_user', to='todo.User'),
        ),
        migrations.AlterField(
            model_name='fanclub',
            name='members',
            field=models.ManyToManyField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='todo.user'), related_name='members', to='todo.User'),
        ),
        migrations.AlterField(
            model_name='fanclub',
            name='top_fans',
            field=models.ManyToManyField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='todo.user'), related_name='top_fans', to='todo.User'),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='admin_clubs',
            field=models.ManyToManyField(blank=True, related_name='admin_clubs', to='todo.Fanclub'),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='following_clubs',
            field=models.ManyToManyField(blank=True, related_name='following_clubs', to='todo.Fanclub'),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='liked_clubs',
            field=models.ManyToManyField(blank=True, related_name='liked_clubs', to='todo.Fanclub'),
        ),
    ]
