# Generated by Django 3.1.7 on 2021-03-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_auto_20210309_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanclub',
            name='admin_members',
            field=models.ManyToManyField(blank=True, related_name='admin_members', to='todo.User'),
        ),
        migrations.AlterField(
            model_name='fanclub',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to='todo.User'),
        ),
        migrations.AlterField(
            model_name='fanclub',
            name='top_fans',
            field=models.ManyToManyField(blank=True, related_name='top_fans', to='todo.User'),
        ),
    ]
