# Generated by Django 3.1.7 on 2021-03-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_auto_20210309_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='media',
            field=models.ImageField(blank=True, upload_to='chats_media'),
        ),
        migrations.AddField(
            model_name='user_detail',
            name='user_profile_image',
            field=models.ImageField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAkjktNk_waKZ6A064JikKQRYLxoKPNIUR_g&usqp=CAU', upload_to='users_media'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='author_image',
            field=models.CharField(max_length=1000),
        ),
    ]
