# Generated by Django 3.1.7 on 2021-03-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0021_auto_20210309_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='user_profile_image',
            field=models.ImageField(blank=True, default='defaultuser.jpg', upload_to='users_media'),
        ),
    ]
