# Generated by Django 3.1.7 on 2021-03-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0022_auto_20210309_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='user_profile_image',
            field=models.ImageField(blank=True, default='users_media/defaultuser.jpg', upload_to='users_media'),
        ),
    ]
