# Generated by Django 3.1.7 on 2021-03-09 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0026_auto_20210309_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['chatroom_id']},
        ),
    ]
