# Generated by Django 3.1.7 on 2021-03-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0027_auto_20210309_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='user_profile_image',
            field=models.ImageField(blank=True, upload_to='users_media'),
        ),
    ]
