# Generated by Django 3.1.7 on 2021-03-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0030_auto_20210310_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='user_status',
            field=models.CharField(blank=True, default='A big lust with movies', max_length=100),
        ),
    ]
