# Generated by Django 3.1.7 on 2021-03-12 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0031_user_detail_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='author_id',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='todo.user'),
            preserve_default=False,
        ),
    ]
