# Generated by Django 3.1.7 on 2021-03-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0032_chat_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanclub',
            name='des',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fanclub',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
