# Generated by Django 3.1.7 on 2021-03-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0036_auto_20210313_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanclub',
            name='image',
            field=models.ImageField(blank=True, default='fanclub_media/Film_Review_Dark_Knight_Rises-085d2-4549.jpg', upload_to='fanclub_media'),
        ),
    ]
