# Generated by Django 3.1.7 on 2021-03-17 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0038_user_detail_recent_clubs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fan_activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_count', models.IntegerField(blank=True)),
                ('fan_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='todo.user')),
                ('fanclub_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='todo.fanclub')),
            ],
            options={
                'ordering': ['activity_count'],
            },
        ),
    ]
