# Generated by Django 3.1.7 on 2021-03-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0039_fan_activity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fan_activity',
            new_name='Fan_activitie',
        ),
    ]
