# Generated by Django 3.1.7 on 2021-03-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0040_auto_20210317_1636'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fan_activitie',
            new_name='Fan',
        ),
    ]
