# Generated by Django 3.1.7 on 2021-03-18 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0042_remove_fanclub_top_fans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fan',
            options={'ordering': ['-activity_count']},
        ),
        migrations.AddField(
            model_name='fan',
            name='last_active',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 19, 0, 59, 8, 556212)),
        ),
        migrations.AlterField(
            model_name='fan',
            name='activity_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
