# Generated by Django 3.1.7 on 2021-03-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0044_auto_20210319_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='last_active_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fan',
            name='last_active_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
