# Generated by Django 3.1.7 on 2021-03-19 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0045_auto_20210319_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='last_active_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fan',
            name='last_active_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
