# Generated by Django 3.1.7 on 2021-03-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0046_auto_20210319_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='user_status',
            field=models.CharField(blank=True, default='A big love with movies', max_length=100),
        ),
    ]
